import './module/buckaroo-payment';
import './api/buckaroo-payment.service';
import './api/buckaroo-payment-settings.service';
import './components/buckaroo-afterpay-old-tax';
import './components/buckaroo-main-config';
import './components/buckaroo-config-card';
import './components/buckaroo-payment-list';
import './components/buckaroo-test-credentials';
import './components/buckaroo-toggle-status';