# yaml-language-server: $schema=https://raw.githubusercontent.com/symfony/routing/7.4/Loader/schema/routing.schema.json
imported_routes:
    resource: ../../**/Storefront/Controller/*Controller.php
    type: attribute
