name: Icon update
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone media repository
        run: |
            git clone https://github.com/buckaroo-it/Media
            ls -lah
      - name: Rename all files to lowercase
        run: |
            cd "${{ github.workspace }}/Media/Payment methods/SVG/"
            rm -f knaken.svg paylink.svg paybybank.svg pos.svg
            cp ${{ github.workspace }}/.github/workflows/rename-icons.php ${{ github.workspace }}/Media/rename-icons.php
            php  ./rename-icons.php
      - name: Copy payment method icons
        run: |
            cd Media
            cp -R "Payment methods/SVG/." ${{ github.workspace }}/src/Resources/views/storefront/buckaroo/payments/
            cp "Payment methods/SVG/creditcards.svg" ${{ github.workspace }}/src/Resources/public/storefront/buckaroo/creditcards.svg
            rm ${{ github.workspace }}/src/Resources/views/storefront/buckaroo/payments/tinka.svg
      - name: Copy creditcards icons
        run: |
            cd Media
            mv "Creditcard issuers/SVG/cartebleue.svg" "Creditcard issuers/SVG/cartebleuevisa.svg"
            cp -R "Creditcard issuers/SVG/." ${{ github.workspace }}/src/Resources/public/storefront/buckaroo/creditcards/
      - name: Copy payment issuers icons
        run: |
            cd Media
            cp -R "iDEAL bank issuers/SVG/." ${{ github.workspace }}/src/Resources/public/storefront/buckaroo/issuers/
            rm -f ${{ github.workspace }}/src/Resources/public/storefront/buckaroo/issuers/handelsbanken.svg
      - name: Cleanup
        run: |
            rm -rd Media
      - name: Create commit if we have changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply logo changes from media repository